<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterShowRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\CharacterShow 
     */
    public function getCharactersOfShow($showID = 0) {
        $query = $this->getEntityManager()->createQueryBuilder()
                        ->from('EssentialTvEtvBundle:CharacterShow', 'charShow')
                        ->select("char")
                        ->leftJoin("EssentialTvEtvBundle:Characters", "char", "WITH", "char.characterId=charShow.csCharacterId")
                        ->where("charShow.csShowId = :showID")
                        ->setParameter('showID', $showID)
                        ->getQuery();
        
        return $query->getResult();
    }

}
