<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSeasonEpisodeRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\CharacterShow 
     */
    public function getMostApperanceOfChar($characterId) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("CSE.cseSeasonId, MAX(CSE.cseApperanceCount) AS MaxCount")
//                ->addSelect("ER.erUserId")
                ->from('EssentialTvEtvBundle:CharacterSeasonEpisode', 'CSE')
//                ->leftJoin("EssentialTvEtvBundle:Episodes", "Ep", "WITH", "Ep.episodeId=CSE.cseEpisodeId")
                ->where('CSE.cseCharacterId = :characterID')
                ->setParameter('characterID', $characterId);


        $strQuery = $query->getQuery();

        return $strQuery->execute();
    }

    public function getEpisodeWiseChar($episodeId) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("C")
//                ->addSelect("U.userFirstName")
//                ->addSelect("C.characterTitle")
//                ->addSelect("C.characterOriginalDataSupersede")
//                ->addSelect("C.characterApiImages")
//                ->addSelect("C.characterBannerImage")
//                ->addSelect("u.userFirstName")
                ->from('EssentialTvEtvBundle:CharacterSeasonEpisode', 'CSE')
                ->leftJoin("EssentialTvEtvBundle:Characters", "C", "WITH", "C.characterId=CSE.cseCharacterId")
                ->where('CSE.cseEpisodeId = :episodeId')
                ->setParameter('episodeId', $episodeId)
                ->orderBy('CSE.cseApperanceCount', 'DESC');


        $strQuery = $query->getQuery();

        return $strQuery->execute();
    }

}
