<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigSettingsRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\Characters 
     */
    public function getAllRows() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT CS.csOption, CS.csValue
                            FROM EssentialTvEtvBundle:ConfigSettings AS CS')
                        ->getResult();
    }

    public function updateOptionValue($csOption = "", $csValue = "") {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->update('EssentialTvEtvBundle:ConfigSettings', 'CS')
                ->set('CS.csValue', $csValue)
                ->where('CS.csOption = :csOption')
                ->setParameter('csOption', $csOption)
                ->getQuery();
        try {
            $qb->execute();
            return true;
        } catch (Exception $e) {
            return false;
        }
    }

}
