<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteFeedbacksRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\QuoteFeedbacks 
     */
    public function countIfFeedbackGiven($userID = 0, $quoteID = 0) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("QF")
                ->from('EssentialTvEtvBundle:QuoteFeedbacks', 'QF')
                ->where('QF.quoteFeedbackUserId = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('QF.quoteFeedbackSpoilerId = :quoteID')
                ->setParameter('quoteID', $quoteID);

        $intCount = count($query->getQuery()->getResult());

        return $intCount;
    }
    
    
    
    public function objIfFeedbackGiven($userID = 0, $quoteID = 0) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("QF")
                ->from('EssentialTvEtvBundle:QuoteFeedbacks', 'QF')
                ->where('QF.quoteFeedbackUserId = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('QF.quoteFeedbackSpoilerId = :quoteID')
                ->setParameter('quoteID', $quoteID);

        return $query->getQuery()->getResult();
    }


}
