<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonsRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\Episodes 
     */
    public function getSeasonsFromShowOrderDesc($showID) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT S
                            FROM EssentialTvEtvBundle:Seasons AS S
                            Where S.seasonShowId = :showID
                            Order By S.seasonCreatedOn DESC')
                        ->setParameter('showID', $showID)
                        ->getResult();
    }
    
    

    public function getSeasonsByCharactersOrderDesc($characterID) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("Sea")
                ->from('EssentialTvEtvBundle:CharacterSeasonEpisode', 'CSE')
                ->leftJoin("EssentialTvEtvBundle:Seasons", "Sea", "WITH", "Sea.seasonId=CSE.cseSeasonId")
                ->where('CSE.cseCharacterId = :characterID')
                ->setParameter('characterID', $characterID)
                ->orderBy('CSE.cseCreatedOn', 'DESC');


        $strQuery = $query->getQuery();

        return $strQuery->execute();
    }

}
