<?php

namespace EssentialTv\EtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpoilerFeedbacksRepository extends EntityRepository {

    /**
     * Get Reaction & Response against that reaction
     *
     * @return \EssentialTv\EtvBundle\Entity\SpoilerFeedbacks 
     */
    public function countIfFeedbackGiven($userID = 0, $spoilerID = 0) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("SF")
                ->from('EssentialTvEtvBundle:SpoilerFeedbacks', 'SF')
                ->where('SF.spoilerFeedbackUserId = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('SF.spoilerFeedbackSpoilerId = :spoilerID')
                ->setParameter('spoilerID', $spoilerID);

        $intCount = count($query->getQuery()->getResult());

        return $intCount;
    }
    
    
    
    public function objIfFeedbackGiven($userID = 0, $spoilerID = 0) {
        $query = $this->getEntityManager()
                ->createQueryBuilder()
                ->select("SF")
                ->from('EssentialTvEtvBundle:SpoilerFeedbacks', 'SF')
                ->where('SF.spoilerFeedbackUserId = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('SF.spoilerFeedbackSpoilerId = :spoilerID')
                ->setParameter('spoilerID', $spoilerID);

        return $query->getQuery()->getResult();
    }

}
